### ISSUE TITLE
Exception koi-worker

### ISSUE THREAD

**Issue by hollis11** [koi-learning/koi-core#48]
Docker container restarts periodically
Message:

> Traceback (most recent call last):
2023-06-22 10:54:32   File "/usr/local/bin/koi-worker", line 8, in 
2023-06-22 10:54:32     sys.exit(main())
2023-06-22 10:54:32   File "/usr/local/lib/python3.8/dist-packages/koi_core/worker.py", line 207, in main
2023-06-22 10:54:32     sec_since_last_change = (datetime.utcnow() - instance.last_modified).total_seconds()
2023-06-22 10:54:32 TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'

**Comment by hannesrichter** [comment]
This was fixed in commit c6f38989d0add774a17552cf0bc603cecbb2046f.
